apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: my-nginx-service
  name: my-nginx-service
  namespace: my-nginx-namespace
spec:
  ports:
  - name: 8888-80
    port: 8888
    protocol: TCP
    targetPort: 80
  selector:
    app: my-nginx-deployment
  type: ClusterIP
status:
  loadBalancer: {}
